# Generated by Django 4.1.7 on 2023-06-05 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 9, 14, 49, 602061), verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='Фамилия'),
        ),
    ]
