# Generated by Django 4.1.7 on 2023-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Kunasyl', max_length=150, unique=True, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Tamabayeva', max_length=150, unique=True, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
